# Hermitian Matrix

To the [Qiskit](https://qiskit.org/) authors, this is:
"necessary to discuss in a study of quantum computation",
even though its importance lies more in the study of quantum mechanics.

A **Hermitian matrix** is simply a matrix that is equal to its *conjugate transpose* (denoted with a  †  symbol).

What is the **conjugate transpose** of a matrix?

This involves two terms, but I'll focus on the procedure, and not the definition:

* to obtain the *conjugate* of a matrix A: 

    * locate any imaginary elements (denoted by *j*) of matrix A. If all elements are real, then you are done and the conjugate of matrix A is matrix A.

    * give each imaginary element the opposite sign, i.e. negate it. So *3j* becomes *-3j*.

* the *transpose* of a matrix A is simply obtained by:

    * locating all elements off its main diagonal
    
    * reflecting it about its main diagonal

Let's build a matrix with complex numbers.

In [1]:
import numpy as np

a = np.array([[1, np.complex(0, 1)], [np.complex(0, -1), 2]])
a

array([[1.+0.j, 0.+1.j],
       [0.-1.j, 2.+0.j]])

Let's see the conjugate of matrix `a`:

In [2]:
a.conjugate()

array([[1.-0.j, 0.-1.j],
       [0.+1.j, 2.-0.j]])

Note that the *j* term appears to be negated, even if its value is 0.
This is just a display effect; `-0.j` and `+0.j` are equivalent.

Now let's see the transpose of matrix `a`:

In [3]:
a.transpose()

array([[1.+0.j, 0.-1.j],
       [0.+1.j, 2.+0.j]])

Note that the top-right and bottom-left elements chosen here are complex conjugates of one another: thus the transpose of `a` is the conjugate of `a`:

In [4]:
a.transpose() == a.conjugate()

array([[ True,  True],
       [ True,  True]])

Let's demonstrate this with the *Pauli-Y* quantum gate, which is Hermitian:

In [5]:
PAULI_Y = np.array([[0, np.complex(0, imag=-1)], [np.complex(0, imag=1), 0]])
PAULI_Y

array([[0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j]])

Note the main diagonal contains all zeros, the elements on the upper-right triangle each are *-j*, and the lower-left triangle contains all *+j* values.

Here's how we know it's Hermitian:

In [10]:
PAULI_Y == PAULI_Y.conjugate().transpose()

array([[ True,  True],
       [ True,  True]])

Let's apply the Pauli-Y gate to our computational basis state `|0>`

In [6]:
basis0 = np.array([[1],[0]])
basis0

array([[1],
       [0]])

In [7]:
np.matmul(PAULI_Y, basis0)

array([[0.+0.j],
       [0.+1.j]])

Note that the top element advanced in phase by 180°, while the bottom advanced by 90°.

And to our computational basis state `|1>`,
let's also apply the Pauli-Y gate.

In [8]:
basis1 = np.array([[0],[1]])
basis1

array([[0],
       [1]])

We *would* expect this to follow the same pattern of the top becoming 1 (+180°) and the bottom becoming *-j* (+90°):

In [9]:
np.matmul(PAULI_Y, basis1)

array([[0.-1.j],
       [0.+0.j]])

...when in fact, the top shifts by -90° and the bottom advances by +180°.