website: `https://qiskit.org/`

page: `https://qiskit.org/textbook/ch-prerequisites/linear_algebra.html`

###### Some terms

What is a **qubit**?

It is a *quantum bit*. In math, it is represented by a
*quantum state vector*.

What is a **quantum state vector**?

A *vector* has magnitude and direction. A *state vector* points to a point in space that corresponds to a particular *quantum state*.

What makes quantum states unique and different?

They contrast to binary states. In conventional computation (e.g., household computers), a bit holds either a 0 or 1 value. 

What makes quantum computing so powerful?

A *quantum bit* (qubit) can hold many more states than just the binary states.

How do we perform *quantum computations*?

We use a *quantum gate* on a *quantum state vector* (qubit).

What is a **quantum gate**?

In math, a *quantum gate* is a matrix.

Let's see a common example:
The *Pauli-X* gate, which behaves like a classical NOT logic gate.

In [4]:
import numpy as np

In [33]:
pauli_x = np.array([[0, 1], [1, 0]])
pauli_x

array([[0, 1],
       [1, 0]])

Now we have a gate. Let's apply it to some *quantum state vectors* (qubits).

create computational basis state `|0>`

In [34]:
basis0 = np.array([[1],[0]])
basis0

array([[1],
       [0]])

create computational basis state `|1>`

In [31]:
basis1 = np.array([[0],[1]])
basis1

array([[0],
       [1]])

Matrix multiplication

In [35]:
np.matmul(pauli_x, basis0)

array([[0],
       [1]])

We can see that the Pauli-X gate performed the logical NOT: 

In [41]:
product1 = np.matmul(pauli_x, basis0) == basis1
product1

array([[ True],
       [ True]])

In [43]:
np.all(product1)

True

The same is true for performing the Pauli-X gate on the `|1>` computational basis vector:

In [44]:
np.all(np.matmul(pauli_x, basis1) == basis0)

True