# Unitary Matrix

This is a key concept at the foundation of Linear Algebra,
as applied to Quantum Computation.
As defined by the [Qiskit](https://qiskit.org/) authors:

> A unitary matrix is very similar (to the Hermitian Matrix). Specifically, it is a matrix such that the inverse matrix is equal to the conjugate transpose of the original matrix.

An example serves best.

In [1]:
import numpy as np

In [2]:
a = np.array([[4, 9], [16, 25]])
a

array([[ 4,  9],
       [16, 25]])

In [3]:
identity = np.identity(2, dtype=int)
identity

array([[1, 0],
       [0, 1]])

In [4]:
np.matmul(a, identity)

array([[ 4,  9],
       [16, 25]])

In [5]:
np.all(np.matmul(a, identity))

True

> Calculating inverse matrices is rarely important in quantum computing. Since most of the matrices we encounter are unitary, we can assume that the inverse is simply given by taking the conjugate transpose.
> 
> The Pauli-Y matrix, in addition to being Hermitian, is also unitary (it is equal to its conjugate transpose, which is also equal to its inverse; therefore, the Pauli-Y matrix is its own inverse!).

Again, a Hermitian matrix is simply a matrix that is equal to its conjugate transpose (denoted with a  †  symbol)

In [6]:
PAULI_Y = np.array([[0, np.complex(0, imag=-1)], [np.complex(0, imag=1), 0]])
PAULI_Y

array([[0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j]])

Here's how we know the Pauli-Y gate is **unitary**:

In [7]:
np.matmul(PAULI_Y, PAULI_Y)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [8]:
identity == np.matmul(PAULI_Y, PAULI_Y)

array([[ True,  True],
       [ True,  True]])

In [9]:
PAULI_Y == np.linalg.inv(PAULI_Y)

array([[ True,  True],
       [ True,  True]])

In [10]:
PAULI_Y == PAULI_Y.conjugate().transpose()

array([[ True,  True],
       [ True,  True]])

Note that beyond a 2 x 2 matrix, this complexity becomes burdensome.

In [11]:
identity_3x3 = np.identity(3, dtype=int)

In [12]:
pos_j = np.complex(0, 1)
neg_j = np.complex(0, -1)

In [13]:
PAULI_Y3 = np.array([[0, neg_j, neg_j], 
                     [pos_j, 0, neg_j], 
                     [pos_j, pos_j, 0]])

PAULI_Y3

array([[0.+0.j, 0.-1.j, 0.-1.j],
       [0.+1.j, 0.+0.j, 0.-1.j],
       [0.+1.j, 0.+1.j, 0.+0.j]])

In [14]:
sanity_check = np.matmul(PAULI_Y3, identity_3x3)
sanity_check == PAULI_Y3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
PAULI_Y3 == PAULI_Y3.conjugate().transpose()

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Note that the 3x3 Pauli-Y gate is a *singular matrix*: its determinant is zero.

In [16]:
np.linalg.det(PAULI_Y3)

0j

In [17]:
try:
    np.linalg.inv(PAULI_Y3)
except:
    print("LinAlgError: Singular matrix")

LinAlgError: Singular matrix
